export const NATIONALITIES = {
	AU: 'AU',
	BR: 'BR',
	CA: 'CA',
	CH: 'CH',
	DE: 'DE',
	DK: 'DK',
	ES: 'ES',
	FI: 'FI',
	FR: 'FR',
	GB: 'GB',
	IE: 'IE',
	NO: 'NO',
	NL: 'NL',
	NZ: 'NZ',
	US: 'US',
	DEFAULT: '',
}

export const NATIONALITIES_HUMAN_NAME = {
	[NATIONALITIES.AU]: 'Australia',
	[NATIONALITIES.BR]: 'Brazil',
	[NATIONALITIES.CA]: 'Canada',
	[NATIONALITIES.CH]: 'Switzerland',
	[NATIONALITIES.DE]: 'Germany',
	[NATIONALITIES.DK]: 'Denmark',
	[NATIONALITIES.ES]: 'Spain',
	[NATIONALITIES.FI]: 'Finland',
	[NATIONALITIES.FR]: 'France',
	[NATIONALITIES.GB]: 'United Kingdom',
	[NATIONALITIES.IE]: 'Ireland',
	[NATIONALITIES.NO]: 'Norway',
	[NATIONALITIES.NL]: 'Netherlands',
	[NATIONALITIES.NZ]: 'New Zealand',
	[NATIONALITIES.US]: 'United States of America',
}